# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       sdk-kickstarter-configs

# >> macros
# << macros

Summary:    Kickstarter configs for Mer SDK
Version:    0.11
Release:    1
Group:      System/Base
License:    Public Domain
BuildArch:  noarch
URL:        https://github.com/lbt/sdk-kickstarter-configs
Source0:    sdk-kickstarter-scripts.tgz
Source100:  sdk-kickstarter-configs.yaml
Requires:   mer-kickstarter-configs
BuildRequires:  mer-kickstarter-configs
BuildRequires:  mer-kickstarter

%description
Configuration files to build Mer SDK and variants

%package -n sdk-kickstarter-ks
Summary:    Kickstarts for the Mer SDK and variants
Group:      System/Base
Requires:   %{name} = %{version}-%{release}

%description -n sdk-kickstarter-ks
Kickstart files to build Mer SDK and variants


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
mkdir kickstarts
mer-kickstarter -c 00sdk.yaml -o kickstarts/
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# sdk-kickstarter-configs
mkdir -p %{buildroot}%{_datadir}/kickstarts/
cp -ar kickstarts/* %{buildroot}%{_datadir}/kickstarts/

# sdk-kickstarter-ks
mkdir -p %{buildroot}%{_datadir}/kickstarter-configs/sdk/
cp -ar *.yaml %{buildroot}%{_datadir}/kickstarter-configs/sdk/

# << install pre

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_datadir}/kickstarter-configs/sdk/*
# >> files
# << files

%files -n sdk-kickstarter-ks
%defattr(-,root,root,-)
%{_datadir}/kickstarts/*
# >> files sdk-kickstarter-ks
# << files sdk-kickstarter-ks
