Name: sdk-kickstarter-configs
Summary: Kickstarter configs for Mer SDK
Description: Configuration files to build Mer SDK and variants
Version: 0.11
Release: 1
Group: System/Base
License: Public Domain
BuildArch: noarch
URL: https://github.com/lbt/sdk-kickstarter-configs
Sources:
    - sdk-kickstarter-scripts.tgz
Requires:
    - mer-kickstarter-configs
PkgBR:
    - mer-kickstarter-configs
    - mer-kickstarter
Configure: none
Builder: none
SetupOptions: -q -n src

Files:
    - "%{_datadir}/kickstarter-configs/sdk/*"

SubPackages:
    - Name:  sdk-kickstarter-ks
      AsWholeName : true
      Summary: Kickstarts for the Mer SDK and variants
      Description: Kickstart files to build Mer SDK and variants
      Group: System/Base
      Files:
        - "%{_datadir}/kickstarts/*"


